"""added systems and equipment

Revision ID: 4a4c961fbc4d
Revises: b0b1074e9cf7
Create Date: 2022-03-27 20:47:08.591408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4c961fbc4d'
down_revision = 'b0b1074e9cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_handling_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model_no', sa.String(length=100), nullable=False),
    sa.Column('serial_no', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('equipment_type', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cooling_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model_no', sa.String(length=100), nullable=False),
    sa.Column('serial_no', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('equipment_type', sa.String(length=100), nullable=False),
    sa.Column('refrigerant_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heating_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model_no', sa.String(length=100), nullable=False),
    sa.Column('serial_no', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('equipment_type', sa.String(length=100), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('work_performed', sa.String(length=1000), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('customer', 'street_address_2',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('maintenance_log', sa.Column('system_id', sa.Integer(), nullable=False))
    op.drop_constraint('maintenance_log_customer_id_fkey', 'maintenance_log', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_log', 'system', ['system_id'], ['id'])
    op.drop_column('maintenance_log', 'customer_id')
    op.add_column('system', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('system', sa.Column('system_type', sa.String(length=100), nullable=False))
    op.add_column('system', sa.Column('heating', sa.Boolean(), nullable=False))
    op.add_column('system', sa.Column('cooling', sa.Boolean(), nullable=False))
    op.add_column('system', sa.Column('notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system', 'notes')
    op.drop_column('system', 'cooling')
    op.drop_column('system', 'heating')
    op.drop_column('system', 'system_type')
    op.drop_column('system', 'name')
    op.add_column('maintenance_log', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'maintenance_log', type_='foreignkey')
    op.create_foreign_key('maintenance_log_customer_id_fkey', 'maintenance_log', 'customer', ['customer_id'], ['id'])
    op.drop_column('maintenance_log', 'system_id')
    op.alter_column('customer', 'street_address_2',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_table('repair_log')
    op.drop_table('heating_equipment')
    op.drop_table('cooling_equipment')
    op.drop_table('air_handling_equipment')
    # ### end Alembic commands ###
